version: "3.8"
services:
  mongodb:
    image: "mongo"
    # Set custom container name, not generated one
    container_name: mongodb
    volumes:
      - data:/data/db
    environment:
      # Option 1 for env var
      - MONGO_INITDB_ROOT_USERNAME=max
      - MONGO_INITDB_ROOT_PASSWORD=secret
      # Option 2 for env var
      # MONGO_INITDB_ROOT_PASSWORD: secret
    # Option 3 for env var
    # env_file:
    #   - ./env/mongo.env
  backend:
    build: ./backend
    # Use below if you have dockerfile with different name as Dockerfile-dev instead of Dockerfile
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile-dev
    #   args:
    #     some-arg: 1
    ports:
      - "80:80"
    volumes:
      # Named volume
      - logs:/app/logs
      # Bind Mount
      - ./backend:/app
      # Anonimous volume
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      # mongodb service should up and running before
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    # set 'stdin_open' and 'tty' to 'true' to replace common 'it' mode
    stdin_open: true
    tty: true

# Only Named volumes should be specofied here
volumes:
  data:
  logs:
