apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  # volumeMode: Block
  volumeMode: Filesystem
  storageClassName: standart
  accessModes:
    - ReadWriteOnce # only for single Node (minikube)
    # - ReadOnlyMany # multiple Nodes
    # - ReadWriteMany # multiple Nodes
  hostPath:
    path: /data
    type: DirectoryOrCreate
