apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    # select app: story from deployment.yaml by 'label'
    app: story
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
